apiVersion: certmanager.k8s.io/v1alpha2
kind: Certificate
metadata:
  name: marcusteh-com-tls
spec:
  secretName: marcusteh-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: marcusteh.com
  dnsNames:
    - marcusteh.com
    - www.marcusteh.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - marcusteh.com
          - www.marcusteh.com
