apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: marcusteh-com-tls
spec:
  secretName: marcusteh-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: marcusteh.com
  dnsNames:
    - marcusteh.com
    - www.marcusteh.com
